name: CI for karsajobs-ui

on:
  push:
    branches:
      - karsajobs-ui

jobs:
  lint-dockerfile:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Lint Dockerfile
        run: |
          # Install hadolint
          sudo wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v2.10.0/hadolint-Linux-x86_64
          sudo chmod +x /bin/hadolint

          # Run hadolint against Dockerfile
          hadolint Dockerfile

  build-app-karsajobs-ui:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Build and Push Docker Image
      run: |
        docker build -t ghcr.io/kingxdeni/karsajobs-ui:latest .
        echo ${{ secrets.GHCR_TOKEN }} | docker login ghcr.io -u kingxdeni --password-stdin
        docker push ghcr.io/kingxdeni/karsajobs-ui:latest
