name: CI for karsajobs

on:
  push:
    branches:
      - karsajobs

jobs:
  lint-dockerfile:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Lint Dockerfile
        run: |
          # Install hadolint
          sudo wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v2.10.0/hadolint-Linux-x86_64
          sudo chmod +x /bin/hadolint

          # Run hadolint against Dockerfile
          hadolint Dockerfile

  test-app:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set Up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Run Unit Tests
      run: go test -v -short --count=1 $(go list ./...)

  build-app-karsajobs:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set Up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build and Push Docker Image
      run: |
        docker build -t ghcr.io/kingxdeni/karsajobs:latest .
        echo ${{ secrets.GHCR_TOKEN }} | docker login ghcr.io -u kingxdeni --password-stdin
        docker push ghcr.io/kingxdeni/karsajobs:latest
